[
  {
    "type": "value_error",
    "loc": [
      "contributor",
      0,
      "Person"
    ],
    "msg": "Value error, Contact person must have an email address.",
    "input": {
      "name": "Last, First",
      "roleName": [
        "dcite:Author",
        "dcite:ContactPerson"
      ],
      "schemaKey": "Person",
      "identifier": "0000-0003-3456-2493",
      "affiliation": [
        {
          "name": "An Institution",
          "roleName": [],
          "schemaKey": "Affiliation",
          "contactPoint": [],
          "includeInCitation": false
        }
      ],
      "includeInCitation": true
    },
    "ctx": {
      "error": "Contact person must have an email address."
    },
    "url": "https://errors.pydantic.dev/2.10/v/value_error"
  }
]