[
  {
    "type": "value_error",
    "loc": [
      "contributor",
      16,
      "Person"
    ],
    "msg": "Value error, Contact person must have an email address.",
    "input": {
      "name": "Frank, L. M.",
      "roleName": [
        "dcite:ContactPerson"
      ],
      "schemaKey": "Person",
      "affiliation": [],
      "includeInCitation": true
    },
    "ctx": {
      "error": "Contact person must have an email address."
    },
    "url": "https://errors.pydantic.dev/2.10/v/value_error"
  }
]