[
  {
    "type": "value_error",
    "loc": [
      "contributor",
      0,
      "Person"
    ],
    "msg": "Value error, Contact person must have an email address.",
    "input": {
      "name": "li, nuo",
      "roleName": [
        "dcite:ContactPerson"
      ],
      "schemaKey": "Person",
      "affiliation": [],
      "awardNumber": "1 R01 NS 112312-01",
      "includeInCitation": false
    },
    "ctx": {
      "error": "Contact person must have an email address."
    },
    "url": "https://errors.pydantic.dev/2.10/v/value_error"
  }
]